### ISSUE TITLE
Is it possible to bind to space/esc/...?

### ISSUE THREAD

**Issue by emptyflask** [Uzaaft/heimdall#5]
Looks like right now there's no way to use space, escape, slash, etc.
example:
```toml
[[bindings]]
key = "Space"
modifiers = ["Alt"]
command = "yabai -m window --toggle zoom-fullscreen; yabai -m space --toggle padding"
```
```
called `Result::unwrap()` on an `Err` value: UnsupportedKey("KeySPACE")
```
